### ISSUE TITLE
Database Account Schema

### ISSUE THREAD

**Issue by chadduffin** [ChicoState/radioSTAR#44]
Database account schema needs to use emails and not usernames.

**Comment by chadduffin** [comment]
Establish correctness of 'AccountSchema = new mongoose.Schema' over 'AccountSchema = mongoose.Schema'.

**Comment by kperkins6** [comment]
Do we need to change it to username? It's just nomenclature--there is no functional difference

**Comment by kperkins6** [comment]
Also as far as i've seen on tutorials & the functionality of the db, 'AccountSchema = new mongoose.Schema'  works

**Comment by jdifuria** [comment]
Officially putting this on the backburner until sprint 4 is complete
