### ISSUE TITLE
Add a relationship between playlist and account

### ISSUE THREAD

**Issue by jdifuria** [ChicoState/radioSTAR#59]
one account to many playlists 
account needs a user_id field
playlist needs a user_id (many) and a playlist_id

**Comment by kperkins6** [comment]
There already exists a playlist: _id, a unique object identifier for each playlist. On top of that there is a 'Playlist Name' which as of now isn't being used for anything except a default value of 'Show Playlist', but could be used for further differentiation. 

I don't really see the value of adding playlists to accounts, this creates a data redundancy -- Playlists are associated with shows, and shows are owned by accounts. Playlists for a user could be retrieved by querying all playlists for a users shows -- But that kind of defeats the purpose of having shows. 

accounts, playlists, shows, and charts all have an '_id' field which is an unique identifier for the object. 

Accounts have a 'username' field which can be queried to retrieve the account, as each account should have a unique username [we will be using email address for this value, I can update it to be email_address if you want it for clarity]

Each playlist already has a 'show' field which refers to the show it was played on.

**Comment by kperkins6** [comment]
If you are looking for User U's last X played tracks, I can build a function to retrieve the last X playlists from each of the users shows -- Giving you the last X played tracks in each of their shows. If you don't see value in retrieving the last X for all of U's shows, then I can just sort them by date and return X number of shows.

**Comment by jdifuria** [comment]
sounds good, thank you kevin @chadduffin you need to read this.
